theme = "tokyonight_storm"

[editor]
mouse = false
cursorline = true
color-modes = true
bufferline = "multiple"
auto-completion= true
lsp.display-inlay-hints = true

[editor.cursor-shape]
insert = "bar"
normal  = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = ["file-encoding", "file-line-ending", "file-type"]
separator = "|"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.indent-guides]
render = true
